### ISSUE TITLE
Nullref in SFE

### ISSUE THREAD

**Issue by StenPetrov** [microsoft/service-fabric-explorer#195]
Service Fabric Explorer throws unhandled exception or crashes with no messages whatsoever  when expanding a cluster in the UI

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.TreeNode.get_Handle()
   at ServiceFabricExplorer.BufferedTreeView.SetCheckBoxState(TreeNode node, Boolean visible)
   at ServiceFabricExplorer.BufferedTreeView.UpdateNodeOnAdd(TreeNode node)
   at ServiceFabricExplorer.MainForm.AddDummyNode(TreeNodeCollection nodes)
   at ServiceFabricExplorer.MainForm.<ExpandNode>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceFabricExplorer.MainForm.<MainTreeView_AfterExpand>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

**Comment by jeffj6123** [comment]
Hello,
This is not the actual Repo for SFE but for SFX(the web view for Service fabric.
